name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: Tests
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest

      - name: Format
        run: cargo fmt -- --check

      - name: Clippy --no-default-features
        run: cargo clippy --no-default-features -- -D warnings

      - name: Clippy -- default
        run: cargo clippy --features=default -- -D warnings

      - name: Clippy --all-features
        run: cargo clippy --all --all-features -- -D warnings

      # Codec

      - name: Clippy -- codec
        run: cargo clippy --no-default-features --features=codec -- -D warnings

      # Compatibility

      - name: Clippy -- std
        run: cargo clippy --no-default-features --features=std -- -D warnings

      - name: Clippy -- futures-io
        run: cargo clippy --no-default-features --features=futures-io -- -D warnings

      - name: Clippy -- embedded-io-async
        run: cargo clippy --no-default-features --features=embedded-io-async -- -D warnings

      - name: Clippy -- embedded-io
        run: cargo clippy --no-default-features --features=embedded-io -- -D warnings

      - name: Clippy -- tokio
        run: cargo clippy --no-default-features --features=tokio -- -D warnings

      # Defmt

      - name: Clippy -- defmt
        run: cargo clippy --no-default-features --features=defmt -- -D warnings

      # Logging

      - name: Clippy -- pretty-hex-fmt
        run: cargo clippy --no-default-features --features="pretty-hex-fmt" -- -D warnings

      - name: Clippy -- char-fmt
        run: cargo clippy --no-default-features --features="char-fmt" -- -D warnings

      - name: Clippy -- log
        run: cargo clippy --no-default-features --features="log" -- -D warnings

      - name: Clippy -- defmt
        run: cargo clippy --no-default-features --features="defmt" -- -D warnings

      - name: Clippy -- tracing
        run: cargo clippy --no-default-features --features="tracing" -- -D warnings

      # Codec, FramedRead, FramedWrite

      - name: Test - codec framed_read and framed_write without (decoder-checks, encoder-checks, buffer-early-shift)
        run: cargo test --no-default-features --features "codec,tokio"

      - name: Test - codec framed_read and framed_write with buffer-early-shift without (decoder-checks, encoder-checks)
        run: cargo test --no-default-features --features "codec,buffer-early-shift"

      # FramedRead

      - name: Test - framed_read with decode-enmpty-buffer without (decoder-checks, buffer-early-shift)
        run: cargo test --no-default-features --features "codec,decode-enmpty-buffer"

      - name: Test - framed_read with decode-enmpty-buffer buffer-early-shift without decoder-checks
        run: cargo test --no-default-features --features "codec,decode-enmpty-buffer,buffer-early-shift"

      - name: Test - framed_read with decoder-checks without buffer-early-shift
        run: cargo test --no-default-features --features "codec,decoder-checks"

      - name: Test - framed_read with decoder-checks and buffer-early-shift
        run: cargo test --no-default-features --features "codec,decoder-checks,buffer-early-shift"

      - name: Test - framed_read with decoder-checks and decode-enmpty-buffer without buffer-early-shift
        run: cargo test --no-default-features --features "codec,decoder-checks,decode-enmpty-buffer"

      - name: Test - framed_read with decoder-checks and decode-enmpty-buffer and buffer-early-shift
        run: cargo test --no-default-features --features "codec,decoder-checks,decode-enmpty-buffer,buffer-early-shift"

      # FramedWrite

      - name: Test - freamed_write with encoder-checks
        run: cargo test --no-default-features --features "codec,encoder-checks"
